import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Analytics } from '@vercel/analytics/react';
import MusicPlayer from "../components/Audio/AudioPlayer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "k1zmt's profile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`!bg-primary ${inter.className}`}>
      <body>
        {children}
          <Analytics />
          <MusicPlayer />
      </body>
    </html>
  );
}