import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '../styles/ff7-ui-fonts.css';
import '../styles/ff7-ui.css';
import MusicPlayer from "@/components/Audio/AudioPlayer";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <MusicPlayer />
        </body>
        <Footer />

    </html>
  );
}
